[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "3QMKuqgLcPaFgRw7HtuAv8xskdz3AyLowTfWHK3p2esW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
