[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "FPdUpsknr5ciGjw1zsFqeEvvaubuaU5nzTp68Ky37mS2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
